version: '3.8'
services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: shift_spectra_backend
    image: 'shift-spectra-backend:local'
    ports:
      - '8000:8000'
    expose:
      - '8000'
    command: /bin/bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 'shift-spectra-frontend:local'
    container_name: shift_spectra_frontend
    ports:
      - '3000:3000'
    expose:
        - '3000'
    depends_on:
      - app
networks:
  default:
    driver: bridge
