"""Initialize

Revision ID: 09bb53d7c262
Revises: 
Create Date: 2023-08-11 10:43:46.760761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '09bb53d7c262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employer',
        sa.Column('identifier', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('identifier', name=op.f('employer_pkey')),
    )
    op.create_index(op.f('employer_identifier_idx'), 'employer', ['identifier'], unique=False)
    op.create_table(
        'shift',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employer_id', sa.Integer(), nullable=False),
        sa.Column('start_shift', sa.DateTime(), nullable=False),
        sa.Column('end_shift', sa.DateTime(), nullable=False),
        sa.Column('start_lunch', sa.DateTime(), nullable=False),
        sa.Column('end_lunch', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['employer_id'], ['employer.identifier'], name=op.f('shift_employer_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('shift_pkey')),
    )
    op.create_index(op.f('shift_id_idx'), 'shift', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('shift_id_idx'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('employer_identifier_idx'), table_name='employer')
    op.drop_table('employer')
    # ### end Alembic commands ###
