"""Changes default for import date field

Revision ID: a207bacfd112
Revises: d3cba82b629f
Create Date: 2023-08-11 14:52:00.639166

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a207bacfd112'
down_revision = 'd3cba82b629f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('import_shift_import_date_idx'), 'import_shift', ['import_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('import_shift_import_date_idx'), table_name='import_shift')
    # ### end Alembic commands ###
