"""Initializes

Revision ID: d3cba82b629f
Revises: 
Create Date: 2023-08-11 14:42:58.815093

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3cba82b629f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employer',
        sa.Column('identifier', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('identifier', name=op.f('employer_pkey')),
    )
    op.create_index(op.f('employer_identifier_idx'), 'employer', ['identifier'], unique=False)
    op.create_table(
        'import_shift',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file', sa.String(length=255), nullable=False),
        sa.Column('import_date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('import_shift_pkey')),
    )
    op.create_index(op.f('import_shift_id_idx'), 'import_shift', ['id'], unique=False)
    op.create_table(
        'shift',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employer_id', sa.Integer(), nullable=False),
        sa.Column('start_shift', sa.DateTime(), nullable=False),
        sa.Column('end_shift', sa.DateTime(), nullable=False),
        sa.Column('start_lunch', sa.DateTime(), nullable=False),
        sa.Column('end_lunch', sa.DateTime(), nullable=False),
        sa.Column('import_shift_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['employer_id'], ['employer.identifier'], name=op.f('shift_employer_id_fkey')),
        sa.ForeignKeyConstraint(['import_shift_id'], ['import_shift.id'], name=op.f('shift_import_shift_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('shift_pkey')),
    )
    op.create_index(op.f('shift_id_idx'), 'shift', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('shift_id_idx'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('import_shift_id_idx'), table_name='import_shift')
    op.drop_table('import_shift')
    op.drop_index(op.f('employer_identifier_idx'), table_name='employer')
    op.drop_table('employer')
    # ### end Alembic commands ###
